admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Default:index }

admin_formpage:
    path:     /form
    defaults: { _controller: AdminBundle:Default:add }

admin_articlepage:
    path:     /article/{id}
    defaults: { _controller: AdminBundle:Default:article }
