admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Article:index }

# Afficher le formulaire de création
admin_new_article:
    path:     /articles/new
    defaults: { _controller: AdminBundle:Article:new }
    methods: [GET]

# Envoyer le formulaire de création
admin_create_article:
    path:     /articles/
    defaults: { _controller: AdminBundle:Article:create }
    methods: [POST]

# Envoyer le formulaire d'édition
admin_update_article:
    path:     /articles/{id}
    defaults: { _controller: AdminBundle:Article:update }
    methods: [PUT]

# Envoyer le formulaire d'édition
admin_publish_article:
    path:     /articles/{id}/publish
    defaults: { _controller: AdminBundle:Article:publish }
    methods: [GET]

# Envoyer le formulaire d'édition
admin_depublish_article:
    path:     /articles/{id}/depublish
    defaults: { _controller: AdminBundle:Article:depublish }
    methods: [GET]


# Afficher le formulaire d'édition
admin_show_article:
    path:     /articles/{id}/
    defaults: { _controller: AdminBundle:Article:show }
    methods: [GET]

# Afficher le formulaire d'édition
admin_edit_article:
    path:     /articles/{id}/edit
    defaults: { _controller: AdminBundle:Article:edit }
    methods: [GET]

# Supprimer l'article
# Hack : GET method used for deletion
admin_delete_article:
    path:     /articles/{id}/delete
    defaults: { _controller: AdminBundle:Article:delete }
