admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Default:index }

admin_formpage:
    path:     /form
    defaults: { _controller: AdminBundle:Default:add }

admin_articlepage:
    path:     /article/{id}
    defaults: { _controller: AdminBundle:Default:article }

admin_editpage:
    path:     /edit/{id}
    defaults: { _controller: AdminBundle:Default:edit }

admin_deletepage:
    path:     /delete/{id}
    defaults: { _controller: AdminBundle:Default:delete }
