admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

home:
    resource: "@HomeBundle/Resources/config/routing.yml"
    prefix:   /home

app:
    resource: '@AppBundle/Controller/'
    type: annotation
