admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

home:
    resource: "@HomeBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

logout:
    path:     /logout

login:
    path:     /login
