home_homepage:
    path:     /
    defaults: { _controller: HomeBundle:Display:index }

home_lifepage:
    path:     /life
    defaults: { _controller: HomeBundle:Display:life }

home_writingpage:
    path:     /mes-ecrits
    defaults: { _controller: HomeBundle:Display:writing }

home_imagespage:
    path:     /en-images
    defaults: { _controller: HomeBundle:Display:images }

home_eventpage:
    path:     /evenements
    defaults: { _controller: HomeBundle:Display:event }

home_newspage:
    path:     /actualites
    defaults: { _controller: HomeBundle:Display:news }

home_showarticle:
    path:     /articles/{id}/
    defaults: { _controller: HomeBundle:Display:show }
    methods: [GET]
