home_homepage:
    path:     /
    defaults: { _controller: HomeBundle:Default:index }

home_lifepage:
    path:     /life
    defaults: { _controller: HomeBundle:Default:life }

home_writingpage:
    path:     /mes-ecrits
    defaults: { _controller: HomeBundle:Default:writing }

home_imagespage:
    path:     /en-images
    defaults: { _controller: HomeBundle:Default:images }

home_eventpage:
    path:     /evenements
    defaults: { _controller: HomeBundle:Default:event }

home_newspage:
    path:     /actualites
    defaults: { _controller: HomeBundle:Default:news }
