home_homepage:
    path:     /
    defaults: { _controller: HomeBundle:Default:index }

home_lifepage:
    path:     /life
    defaults: { _controller: HomeBundle:Default:life }

home_writingpage:
    path:     /writing
    defaults: { _controller: HomeBundle:Default:writing }
